// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: comm/comm.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KNNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataPoint float32 `protobuf:"fixed32,1,opt,name=data_point,json=dataPoint,proto3" json:"data_point,omitempty"` // The query point
	K         int32   `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`                                   // Number of nearest neighbors
}

func (x *KNNRequest) Reset() {
	*x = KNNRequest{}
	mi := &file_comm_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KNNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KNNRequest) ProtoMessage() {}

func (x *KNNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KNNRequest.ProtoReflect.Descriptor instead.
func (*KNNRequest) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{0}
}

func (x *KNNRequest) GetDataPoint() float32 {
	if x != nil {
		return x.DataPoint
	}
	return 0
}

func (x *KNNRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type KNNResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighbors []*Neighbor `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"` // List of nearest neighbors
}

func (x *KNNResponse) Reset() {
	*x = KNNResponse{}
	mi := &file_comm_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KNNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KNNResponse) ProtoMessage() {}

func (x *KNNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KNNResponse.ProtoReflect.Descriptor instead.
func (*KNNResponse) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{1}
}

func (x *KNNResponse) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type Neighbor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataPoint float32 `protobuf:"fixed32,1,opt,name=data_point,json=dataPoint,proto3" json:"data_point,omitempty"` // The neighbor's data point
	Distance  float32 `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`                    // Distance to the query point
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_comm_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{2}
}

func (x *Neighbor) GetDataPoint() float32 {
	if x != nil {
		return x.DataPoint
	}
	return 0
}

func (x *Neighbor) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_comm_comm_proto protoreflect.FileDescriptor

var file_comm_comm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6b, 0x6e, 0x6e, 0x22, 0x39, 0x0a, 0x0a, 0x4b, 0x4e, 0x4e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x6b, 0x22, 0x3a, 0x0a, 0x0b, 0x4b, 0x4e, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x09, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x6e, 0x6e, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x72, 0x52, 0x09, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x22, 0x45, 0x0a,
	0x08, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x64,
	0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x32, 0x48, 0x0a, 0x0a, 0x4b, 0x4e, 0x4e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x4b, 0x4e, 0x65, 0x61, 0x72, 0x65,
	0x73, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x12, 0x0f, 0x2e, 0x6b, 0x6e,
	0x6e, 0x2e, 0x4b, 0x4e, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6b,
	0x6e, 0x6e, 0x2e, 0x4b, 0x4e, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c,
	0x5a, 0x1a, 0x64, 0x69, 0x73, 0x74, 0x73, 0x79, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x67, 0x2f, 0x6b, 0x6e, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_comm_proto_rawDescOnce sync.Once
	file_comm_comm_proto_rawDescData = file_comm_comm_proto_rawDesc
)

func file_comm_comm_proto_rawDescGZIP() []byte {
	file_comm_comm_proto_rawDescOnce.Do(func() {
		file_comm_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_comm_proto_rawDescData)
	})
	return file_comm_comm_proto_rawDescData
}

var file_comm_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_comm_comm_proto_goTypes = []any{
	(*KNNRequest)(nil),  // 0: knn.KNNRequest
	(*KNNResponse)(nil), // 1: knn.KNNResponse
	(*Neighbor)(nil),    // 2: knn.Neighbor
}
var file_comm_comm_proto_depIdxs = []int32{
	2, // 0: knn.KNNResponse.neighbors:type_name -> knn.Neighbor
	0, // 1: knn.KNNService.FindKNearestNeighbors:input_type -> knn.KNNRequest
	1, // 2: knn.KNNService.FindKNearestNeighbors:output_type -> knn.KNNResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_comm_comm_proto_init() }
func file_comm_comm_proto_init() {
	if File_comm_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comm_comm_proto_goTypes,
		DependencyIndexes: file_comm_comm_proto_depIdxs,
		MessageInfos:      file_comm_comm_proto_msgTypes,
	}.Build()
	File_comm_comm_proto = out.File
	file_comm_comm_proto_rawDesc = nil
	file_comm_comm_proto_goTypes = nil
	file_comm_comm_proto_depIdxs = nil
}
